### ISSUE TITLE
 module 'torchvision.models' has no attribute 'VGG16_Weights'

### ISSUE THREAD

**Issue by fabricesenger** [guiwitz/napari-convpaint#13]
hello i installed convpaint into my existing napari.
I create the "annotations" and "prediction" layers, do the annotations forground , background on a single tif image and when i click "train model on single image" i get the error : " module 'torchvision.models' has no attribute 'VGG16_Weights'"

Thank you in advance for your support,

Fabrice.

**Comment by guiwitz** [comment]
Hi @fabricesenger, thanks for trying out the plugin!
Most probably you have a too old version of torchvision installed. How did you install napari and the plugin?

**Comment by fabricesenger** [comment]
Hello, 

I installed the plugin in an existing version of napari together with other lots of plugins. 
Napari is the latest stable version and I re-installed torchvision wich seems to be the latest as well. 
I think I will create a clean install in a dedicated env and let you know how it goes. 


De: "Guillaume Witz" ***@***.***> 
À: "guiwitz/napari-convpaint" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 27 Novembre 2023 22:47:20 
Objet: Re: [guiwitz/napari-convpaint] module 'torchvision.models' has no attribute 'VGG16_Weights' (Issue #13) 





Hi [ https://github.com/fabricesenger | @fabricesenger ] , thanks for trying out the plugin! 
Most probably you have a too old version of torchvision installed. How did you install napari and the plugin?

**Comment by guiwitz** [comment]
I double-checked and torchvision needs to be at least 0.13, so fairly recent. I will add this constraint in the dependencies.

**Comment by fabricesenger** [comment]
Hello, when i check my torch i get this output : 

Name: torch 
Version: 1.10.1+cu113 
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration 
Home-page: https://pytorch.org/ 
Author: PyTorch Team 
Author-email: ***@***.*** 
License: BSD-3 
Location: c:\users\fabrice_senger\miniconda3\envs\napari-env\lib\site-packages 
Requires: typing-extensions 
Required-by: cellpose, napari-convpaint, napari-segment-anything, torchaudio, torchvision 

should be fine , no ? 


De: "Guillaume Witz" ***@***.***> 
À: "guiwitz/napari-convpaint" ***@***.***> 
Cc: "FABRICE SENGER" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 28 Novembre 2023 11:05:55 
Objet: Re: [guiwitz/napari-convpaint] module 'torchvision.models' has no attribute 'VGG16_Weights' (Issue #13) 





I double-checked and torchvision needs to be at least 0.13, so fairly recent. I will add this constraint in the dependencies.

**Comment by fabricesenger** [comment]
upgrade done :
(napari-env) C:\Users\fabrice_senger>pip install --upgrade torch torchvision
Requirement already satisfied: torch in c:\users\fabrice_senger\miniconda3\envs\napari-env\lib\site-packages (1.10.1+cu113)
Collecting torch
  Downloading torch-2.1.1-cp39-cp39-win_amd64.whl (192.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 192.2/192.2 MB 839.6 kB/s eta 0:00:00
Requirement already satisfied: torchvision in c:\users\fabrice_senger\miniconda3\envs\napari-env\lib\site-packages (0.11.2+cu113)
Collecting torchvision
  Downloading torchvision-0.16.1-cp39-cp39-win_amd64.whl (1.1 MB)

Now training has started. Will let you know how it goes.

Best,

Fabrice.

**Comment by fabricesenger** [comment]
![image](https://github.com/guiwitz/napari-convpaint/assets/99400822/1ffc5b6e-7907-4cdd-9950-dd3b6635e67a)

**Comment by guiwitz** [comment]
Ok great to know! The plugin is still very much alpha, so just let me know if you encounter other problems! And yes, in general versions conflicts can be a pain, especially when dealing with complex packages like PyTorch.
